### ISSUE TITLE
Fix cancel_all_subscriptions API

### ISSUE THREAD

**Issue by ryanRfox** [ryanRfox/bitshares-core#3]
## USER STORY
As an API Client the the `set_subscribe_callback` function will always clear filters. 

Current implementation calls `set_subscribe_callback( std::function<void(const fc::variant&)>(), true)`

Using `true` as the second parameter here meant to clear filters according to the API documentation (reference needed), but the documentation is wrong. The `set_subscribe_callback` function will always clear filters, and its second parameter is for something else. Setting it to `true` may trigger an exception.

## TASK LIST
- [ ] Test case
- [ ] Fix code
  - [ ] Rewrite `cancel_all_subscriptions` to do real cleanups
  - [ ] Refactor it and `set_subscribe_callback` to call same cleanup function rather than having same code in both functions.
- [ ] QA/Testing
- [ ] Update documentation
  - [x] Documentation updated in Develop branch (reference needed)

**Comment by ryanRfox** [comment]
Original Issue text:
"For clients, it's not broken. However, the implementation need to be improved. It now calls `set_subscribe_callback( std::function<void(const fc::variant&)>(), true)`. I think using `true` as the second parameter here meant to clear filters according to the API document, but the document was wrong. The `set_subscribe_callback` function will always clear filters, and its second parameter is for something else, setting it to `true` may trigger an exception."
