### ISSUE TITLE
New Issue Template

### ISSUE THREAD

**Issue by ryanRfox** [ryanRfox/bitshares-core#4]
## USER STORY
As a `<persona>` I want `<some functionality>` so that `<some benefit is realized>`.

At minimum, please define the `<who>`, `<what>` and `<why>` for the Issue. 

## TASK LIST
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

## EFFORT ESTIMATION
 - [ ] User Stories / Requirements
 - [ ] Development
 - [ ] QA / Testing
 - [ ] Documentation
