### ISSUE TITLE
Change hard-coded limitations in API's to configurable

### ISSUE THREAD

**Issue by ryanRfox** [ryanRfox/bitshares-core#9]
Change those `FC_ASSERT( limit <= 100 )` limitations to configurable. Inspired by https://github.com/bitshares/bitshares-core/issues/781#issuecomment-375962114.
- [ ] change them to configurable
- [ ] add API to fetch the configured values (https://github.com/ryanrfox/bitshares-core/issues/10)
- [ ] add restricted API for service providers to change the values on the fly (without restarting the server)
  - [ ] maybe remember changed value. Not easy since we're using (almost) read-only `config.ini` and startup parameters right now.
